### ISSUE TITLE
RTX_003_Pipeline shadows not working

### ISSUE THREAD

**Issue by ceccocats** [corporateshark/lightweightvk#54]
Hi,
I was testing with RTX_003_Pipeline and I noticed that shadows are not working:
<img width="1922" height="1207" alt="Image" src="https://github.com/user-attachments/assets/0e7ddc57-6b5b-442d-b3e4-df053595112b" />

It looks like `codeMissShadow` is never called

Minor notes:
The sample don't compile on my PC (ubuntu 22.04, gcc 11.4.0) as it is, giving `unterminated string error` on the `UBOS_AND_PUSH_CONSTANTS` define:
```
RTX_003_Pipeline.cpp:25:3: error: unterminated raw string
   25 |   R"(
      |   ^ 
```
I solved by putting `\` at the end of every line of the define.

Thanks,
Francesco
